### ISSUE TITLE
ScraperWiki.select or ScraperWiki.save_sqlite first?

### ISSUE THREAD

**Issue by GildedHonour** [scraperwiki/scraperwiki-ruby#24]
If I do this 

```
  items.each do |item|
    if ScraperWiki.select("* from swdata where ....).empty? 
       ScraperWiki.save_sqlite(["key123"], item)
     else
       puts "Skipping " + item["key123"]
     end
 end
```

and the db (or rather table) doesn't exist then I get an exception. 

```
/Users/alex/.rvm/gems/ruby-2.1.2/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:49:in `rescue in execute': no such table: swdata (SqliteMagic::NoSuchTable)
  from /Users/alex/.rvm/gems/ruby-2.1.2/gems/sqlite_magic-0.0.3/lib/sqlite_magic.rb:42:in `execute'
  from /Users/alex/.rvm/gems/ruby-2.1.2/gems/scraperwiki-3.0.2/lib/scraperwiki.rb:186:in `select
```

How can I handle that?

**Comment by henare** [comment]
PlanningAlerts [does this](https://www.planningalerts.org.au/how_to_write_a_scraper) in a very hacky way with most of our scrapers:

``` ruby
if (ScraperWiki.select("* from swdata where ....").empty? rescue true)
  ScraperWiki.save_sqlite(["key123"], item)
else
  puts "Skipping " + item["key123"]
end
```
